spring.datasource.url=jdbc:mysql://mysql8-plantsync.mysql.database.azure.com:3306/plantsyncdb?sslMode=REQUIRED&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=dev
spring.datasource.password=${PSPASSWORD}